spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tripwise
    username: postgres
    password: Piyush@2004

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9yVHJpcFdpc2VKV1RBdXRoZW50aWNhdGlvbjEyMzQ1Njc4OTA=
  expiration: 86400000

server:
  port: 8080