spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tripwise
    username: postgres
    password: Piyush@2004

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

file:
  storage:
    location: uploads

server:
  port: 8080