spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tripwise
    username: postgres
    password: Piyush@2004
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080