name: TripWise CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read
  packages: write

jobs:
  backend-build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: tripwise_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d tripwise_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_URL: jdbc:postgresql://localhost:5432/tripwise_test
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: Dlsok0mhIF8FzSZkRh8p+5esHWIWcloIAGqV+YhxnxU=
      JWT_EXPIRATION: 86400000
      CORS_ALLOWED_ORIGINS: http://localhost:5173
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test backend
        working-directory: backend
        run: mvn clean verify

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: false
          load: true
          tags: |
            tripwise-backend:ci

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GHCR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag tripwise-backend:ci \
            ghcr.io/piyushkumar481/tripwise-backend:latest

          docker tag tripwise-backend:ci \
            ghcr.io/piyushkumar481/tripwise-backend:${{ github.sha }}

          docker push \
            ghcr.io/piyushkumar481/tripwise-backend:latest

          docker push \
            ghcr.io/piyushkumar481/tripwise-backend:${{ github.sha }}
